"""
download_data.py
----------------
Business question: Collect 3 years of daily OHLCV price history for AAPL,
TSLA, NVDA, and MSFT (2022-01-03 to 2024-12-31) as the shared foundation
for all three portfolio projects.

Primary source: Yahoo Finance via yfinance.
Fallback: Synthetic data generated by Geometric Brownian Motion (GBM) with
          per-ticker drift/volatility calibrated to approximate real-world
          behavior. The README notes which source was used.

Output: data/raw/stocks_raw.csv
Columns: date, ticker, open, high, low, close, volume
"""

import os
import sys
import warnings
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TICKERS = ["AAPL", "TSLA", "NVDA", "MSFT"]
START_DATE = "2022-01-03"
END_DATE = "2024-12-31"
# yfinance end is exclusive, so fetch through Jan 1 2025
YFINANCE_END = "2025-01-01"

OUTPUT_PATH = Path("data/raw/stocks_raw.csv")

# GBM parameters — approximate annualized drift and volatility per ticker
# Drift/vol are rough real-world calibrations; exact values don't matter
# because the GBM path is only a fallback for offline environments.
GBM_PARAMS = {
    "AAPL": {"start_price": 177.57, "mu": 0.15, "sigma": 0.27, "avg_volume": 80_000_000},
    "TSLA": {"start_price": 399.93, "mu": 0.10, "sigma": 0.65, "avg_volume": 100_000_000},
    "NVDA": {"start_price": 294.11, "mu": 0.80, "sigma": 0.65, "avg_volume": 50_000_000},
    "MSFT": {"start_price": 336.32, "mu": 0.18, "sigma": 0.25, "avg_volume": 25_000_000},
}

RANDOM_SEED = 42  # reproducibility


# ---------------------------------------------------------------------------
# yfinance download
# ---------------------------------------------------------------------------

def download_from_yfinance() -> Optional[pd.DataFrame]:
    """
    Attempt to download OHLCV data from Yahoo Finance.

    Returns a tidy DataFrame with columns [date, ticker, open, high, low,
    close, volume], or None if the download fails.
    """
    try:
        import yfinance as yf

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            raw = yf.download(
                tickers=TICKERS,
                start=START_DATE,
                end=YFINANCE_END,
                auto_adjust=True,
                progress=False,
            )

        if raw.empty:
            print("yfinance returned an empty DataFrame.")
            return None

        # raw has a MultiIndex column: (Price, Ticker)
        # Stack the ticker level to get long format.
        df = raw.stack(level=1, future_stack=True).reset_index()
        df.columns = [c.lower() for c in df.columns]

        # Rename 'level_1' or 'ticker' depending on yfinance version
        if "level_1" in df.columns:
            df = df.rename(columns={"level_1": "ticker"})

        df = df.rename(columns={"date": "date"})
        df["date"] = pd.to_datetime(df["date"]).dt.date

        # Keep and reorder target columns
        df = df[["date", "ticker", "open", "high", "low", "close", "volume"]]
        df = df.sort_values(["ticker", "date"]).reset_index(drop=True)

        # Drop any rows where all price columns are NaN (e.g. non-trading days
        # that yfinance sometimes includes for multi-ticker downloads)
        df = df.dropna(subset=["open", "high", "low", "close"])

        return df

    except Exception as exc:
        print(f"yfinance download failed: {exc}")
        return None


# ---------------------------------------------------------------------------
# GBM fallback
# ---------------------------------------------------------------------------

def generate_trading_dates() -> list:
    """Return a list of weekday dates between START_DATE and END_DATE."""
    all_dates = pd.date_range(start=START_DATE, end=END_DATE, freq="B")
    return [d.date() for d in all_dates]


def generate_gbm_ticker(
    ticker: str,
    dates: list,
    params: dict,
    rng: np.random.Generator,
) -> pd.DataFrame:
    """
    Simulate daily OHLCV data for one ticker using Geometric Brownian Motion.

    High and low are approximated as close ± intraday_range derived from
    sigma; open is yesterday's close with a small gap. Volume is log-normal
    noise around the ticker's average.
    """
    n = len(dates)
    dt = 1 / 252
    mu = params["mu"]
    sigma = params["sigma"]
    s0 = params["start_price"]
    avg_vol = params["avg_volume"]

    # Daily log returns: (mu - 0.5*sigma^2)*dt + sigma*sqrt(dt)*Z
    log_returns = (mu - 0.5 * sigma**2) * dt + sigma * np.sqrt(dt) * rng.standard_normal(n)
    prices = s0 * np.exp(np.cumsum(log_returns))

    # Intraday range ~ sigma * price * sqrt(dt) scaled by a random factor
    intraday_range = sigma * prices * np.sqrt(dt) * rng.uniform(0.5, 2.0, n)
    high = prices + intraday_range * rng.uniform(0.3, 0.7, n)
    low = prices - intraday_range * rng.uniform(0.3, 0.7, n)
    low = np.maximum(low, prices * 0.5)  # floor at 50% of close (sanity check)

    # Open: previous close + small gap noise
    open_ = np.roll(prices, 1)
    open_[0] = s0
    open_ = open_ * (1 + rng.normal(0, sigma * np.sqrt(dt) * 0.3, n))

    # Volume: log-normal around avg_volume
    volume = rng.lognormal(
        mean=np.log(avg_vol),
        sigma=0.3,
        size=n,
    ).astype(np.int64)

    return pd.DataFrame(
        {
            "date": dates,
            "ticker": ticker,
            "open": np.round(open_, 2),
            "high": np.round(high, 2),
            "low": np.round(low, 2),
            "close": np.round(prices, 2),
            "volume": volume,
        }
    )


def generate_synthetic_data() -> pd.DataFrame:
    """Generate synthetic OHLCV data for all tickers via GBM."""
    print("Generating synthetic data via Geometric Brownian Motion...")
    rng = np.random.default_rng(seed=RANDOM_SEED)
    dates = generate_trading_dates()

    frames = [
        generate_gbm_ticker(ticker, dates, GBM_PARAMS[ticker], rng)
        for ticker in TICKERS
    ]
    df = pd.concat(frames, ignore_index=True)
    return df.sort_values(["ticker", "date"]).reset_index(drop=True)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    print("Attempting Yahoo Finance download...")
    df = download_from_yfinance()

    if df is not None:
        source = "Yahoo Finance (yfinance)"
        print(f"Download succeeded: {len(df):,} rows across {df['ticker'].nunique()} tickers.")
    else:
        print("Falling back to synthetic GBM data.")
        df = generate_synthetic_data()
        source = "Synthetic GBM (fallback — yfinance unavailable)"

    df.to_csv(OUTPUT_PATH, index=False)

    # Summary
    print(f"\nData source: {source}")
    print(f"Saved to:    {OUTPUT_PATH}")
    print(f"Shape:       {df.shape}")
    print(f"\nRow counts per ticker:")
    print(df.groupby("ticker").size().to_string())
    print(f"\nDate range:  {df['date'].min()} to {df['date'].max()}")
    print(f"\nFirst 5 rows:")
    print(df.head().to_string(index=False))


if __name__ == "__main__":
    main()
